import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import { Command } from "commander";
import { type Hex, parseSignature } from "viem";
import { canonicalSha256Base64Url } from "../src/canonical.js";
import { verifyConformanceCase } from "../src/verifier.js";
import {
  NormalizedRecordSchema,
  SignedArtifactBundleSchema,
  createValidCase,
} from "./generate-fixtures.js";

const PLACEHOLDER_TRANSACTION_HASH = `0x${"0".repeat(64)}`;

interface Options {
  artifact: string;
  normalized: string;
  output: string;
  authorizationOutput: string;
  preparedAuthorization?: string;
}

async function readJson(path: string): Promise<unknown> {
  return JSON.parse(await readFile(path, "utf8")) as unknown;
}

const program = new Command()
  .name("compose-public-evm-case")
  .description("Compose one transaction-ready public EVM conformance case")
  .requiredOption("--artifact <path>", "signed AP2 artifact generated by the pinned pipeline")
  .requiredOption("--normalized <path>", "independently normalized AP2 record")
  .requiredOption("--output <path>", "standalone conformance case output")
  .requiredOption(
    "--authorization-output <path>",
    "transaction-ready EIP-3009 authorization output",
  )
  .option(
    "--prepared-authorization <path>",
    "require the recorded authorization to match an earlier prepared authorization",
  );

program.parse();
const options = program.opts<Options>();
const signedBundle = SignedArtifactBundleSchema.parse(await readJson(resolve(options.artifact)));
const normalizedInput = (await readJson(resolve(options.normalized))) as {
  records?: unknown[];
};
if (!Array.isArray(normalizedInput.records) || normalizedInput.records.length !== 1) {
  throw new Error("Expected exactly one normalized AP2 record.");
}
if (signedBundle.cases.length !== 1) {
  throw new Error("Expected exactly one signed AP2 artifact.");
}
const normalized = NormalizedRecordSchema.parse(normalizedInput.records[0]);
const signed = signedBundle.cases[0];
if (signed === undefined) throw new Error("The signed AP2 artifact is missing.");

const transactionHash = normalized.paymentReceipt.network_confirmation_id;
if (transactionHash === null || transactionHash === undefined) {
  throw new Error("The AP2 payment receipt is missing its network confirmation id.");
}
const prepared = transactionHash.toLowerCase() === PLACEHOLDER_TRANSACTION_HASH;
const conformanceCase = await createValidCase(normalized, signed, signedBundle, {
  resourceUrl:
    "https://github.com/shibutatsu/pulse-ap2-x402-conformance/tree/main/fixtures/public-evm",
  resourceDescription: "Public Base Sepolia USDC settlement evidence fixture",
  caseDescription: prepared
    ? "Transaction-ready AP2 to x402 EIP-3009 public settlement preparation."
    : "AP2 to x402 EIP-3009 case bound to a public Base Sepolia USDC settlement.",
});
const report = await verifyConformanceCase(conformanceCase);
if (!report.consistent) {
  throw new Error(
    `The composed public EVM case failed offline verification: ${JSON.stringify(report.failures)}`,
  );
}

const authorization = conformanceCase.x402.payload.payload.authorization;
const signature = conformanceCase.x402.payload.payload.signature as Hex;
const parsedSignature = parseSignature(signature);
if (parsedSignature.v === undefined) throw new Error("Expected an ECDSA recovery value.");
const authorizationIdentity = {
  network: conformanceCase.x402.requirements.network,
  chainId: Number(conformanceCase.x402.requirements.network.slice("eip155:".length)),
  asset: conformanceCase.x402.requirements.asset,
  function:
    "transferWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)",
  arguments: {
    from: authorization.from,
    to: authorization.to,
    value: authorization.value,
    validAfter: authorization.validAfter,
    validBefore: authorization.validBefore,
    nonce: authorization.nonce,
    v: Number(parsedSignature.v),
    r: parsedSignature.r,
    s: parsedSignature.s,
  },
  signature,
};
const authorizationHash = canonicalSha256Base64Url(authorizationIdentity);
if (options.preparedAuthorization !== undefined) {
  const earlier = (await readJson(resolve(options.preparedAuthorization))) as {
    authorizationHash?: unknown;
  };
  if (earlier.authorizationHash !== authorizationHash) {
    throw new Error("The recorded authorization does not match the prepared authorization.");
  }
}
const authorizationRecord = {
  requestVersion: "pulse-public-evm-authorization/0.1",
  state: prepared ? "prepared" : "recorded",
  warning:
    "The payer key is a public fixture key. Fund testnet addresses only and never reuse it for assets with value.",
  ...authorizationIdentity,
  authorizationHash,
  expectedTransactionHash: transactionHash,
  caseInputHash: conformanceCase.inputHash,
};

await Promise.all([
  writeFile(resolve(options.output), `${JSON.stringify(conformanceCase, null, 2)}\n`, {
    encoding: "utf8",
    flag: "wx",
  }),
  writeFile(
    resolve(options.authorizationOutput),
    `${JSON.stringify(authorizationRecord, null, 2)}\n`,
    { encoding: "utf8", flag: "wx" },
  ),
]);
process.stdout.write(
  `${prepared ? "Prepared" : "Recorded"} public EVM case ${conformanceCase.id}; offline verification passed.\n`,
);
