export const CONFORMANCE_FAILURE_CODES = [
  "INPUT_SCHEMA_INVALID",
  "INPUT_HASH_MISMATCH",
  "AP2_CRYPTOGRAPHIC_EVIDENCE_INVALID",
  "AP2_CLOSED_MANDATE_UNVERIFIED",
  "AP2_OPEN_MANDATE_UNVERIFIED",
  "AP2_KEY_BINDING_UNVERIFIED",
  "AP2_CHECKOUT_BINDING_UNVERIFIED",
  "AP2_RECEIPT_UNVERIFIED",
  "AP2_CLOSED_MANDATE_REFERENCE_MISMATCH",
  "AP2_CLOSED_MANDATE_CLAIMS_HASH_MISMATCH",
  "AP2_OPEN_MANDATE_CLAIMS_HASH_MISMATCH",
  "AP2_PAYMENT_REFERENCE_MISMATCH",
  "AP2_CLOSED_TRANSACTION_ID_MISMATCH",
  "AP2_CONSTRAINT_VIOLATION",
  "AP2_UNSUPPORTED_CONSTRAINT",
  "AP2_OPEN_PRESET_MISMATCH",
  "AP2_VERIFICATION_CONTEXT_MISMATCH",
  "AP2_MANDATE_TIME_INVALID",
  "AP2_PAYMENT_INSTRUMENT_NOT_ALLOWED",
  "AP2_RECEIPT_NOT_SUCCESSFUL",
  "AP2_RECEIPT_REFERENCE_MISMATCH",
  "AP2_RECEIPT_TRANSACTION_MISMATCH",
  "AP2_X402_SCHEME_MISMATCH",
  "AP2_X402_NETWORK_MISMATCH",
  "AP2_X402_ASSET_MISMATCH",
  "AP2_X402_AMOUNT_MISMATCH",
  "AP2_X402_PAYEE_MISMATCH",
  "AP2_X402_COMMERCE_BINDING_MISMATCH",
  "AP2_X402_TIMEOUT_MISMATCH",
  "AP2_X402_EIP712_DOMAIN_MISMATCH",
  "X402_MANDATE_REFERENCE_MISMATCH",
  "X402_ACCEPTED_REQUIREMENTS_MISMATCH",
  "X402_UNSUPPORTED_EXTENSION",
  "EIP3009_PAYER_MISMATCH",
  "EIP3009_RECIPIENT_MISMATCH",
  "EIP3009_VALUE_MISMATCH",
  "EIP3009_VALID_AFTER_IN_FUTURE",
  "EIP3009_VALID_BEFORE_EXPIRED",
  "EIP3009_VALIDITY_EXCEEDS_TIMEOUT",
  "EIP3009_VALIDITY_EXCEEDS_AP2_EXPIRY",
  "EIP3009_NONCE_BINDING_MISMATCH",
  "EIP3009_SIGNATURE_INVALID",
  "SETTLEMENT_FAILED",
  "SETTLEMENT_NETWORK_MISMATCH",
  "SETTLEMENT_PAYER_MISMATCH",
  "SETTLEMENT_AMOUNT_MISMATCH",
  "SETTLEMENT_TRANSACTION_INVALID",
] as const;

export type ConformanceFailureCode = (typeof CONFORMANCE_FAILURE_CODES)[number];

export interface ConformanceFailure {
  code: ConformanceFailureCode;
  path: string;
  message: string;
  expected?: string | number | boolean | null;
  actual?: string | number | boolean | null;
}
